main: ru.gyruasha.drinkPatch.DrinkPatchPlugin
name: DrinkPatch
author: gyruasha
version: 1.0.0
api-version: '1.20'
# Replace "kit" with the name of your command.
commands:
  drinkinfo:
    description: Turn on/off command message about drinks
    usage: /<drinkinfo> on|off